services:
  app:
    build: # "context" and "dockerfile" fields have to be under "build"
      context: ../
      dockerfile: service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
